import {
  DimensionItem,
  ModuleCategory,
  ModuleItem,
  PriorityItem,
  Question,
  QuizQuestion,
} from './types';

export const GENERIC_PROFESSION_VALUE = 'Generic / show me every module';

export const PROFESSION_OPTIONS: string[] = [
  'Sales',
  'Marketing',
  'Pharmaceutical Industry',
  'Healthcare',
  'Education',
  'Finance and Accounting',
  'Human Resources',
  'Business Management',
  'Information Technology',
  'Software Development',
  'Research',
  'Engineering',
  'Manufacturing',
  'Entrepreneurship',
  'Freelancing',
  'Student',
  'Job Seeker',
  'Content Creation',
  'Customer Service',
  'Legal Services',
  'Government Administration',
  'Other',
  'Generic / show me every module',
];

export const PROFESSION_TO_RELEVANT_TAGS: Record<string, string[]> = {
  Sales: ['sales', 'communication', 'strategy', 'analytics', 'presentations', 'decision_support'],
  Marketing: ['marketing', 'campaigns', 'content', 'creative', 'multimedia', 'analytics', 'communication', 'presentations'],
  'Pharmaceutical Industry': ['research', 'data_analysis', 'analytics', 'communication', 'presentations', 'strategy', 'professional_workflow', 'verification'],
  Healthcare: ['research', 'verification', 'critical_thinking', 'communication', 'data_analysis', 'knowledge_management'],
  Education: ['communication', 'presentations', 'writing', 'knowledge_management'],
  'Finance and Accounting': ['data_analysis', 'analytics', 'excel', 'roi', 'verification'],
  'Human Resources': ['communication', 'governance', 'writing', 'decision_support'],
  'Business Management': ['strategy', 'decision_support', 'roi', 'project_management', 'productivity', 'implementation'],
  'Information Technology': ['coding', 'app_development', 'automation', 'integration', 'agents', 'tool_selection'],
  'Software Development': ['coding', 'app_development', 'agents', 'automation', 'integration'],
  Research: ['research', 'verification', 'knowledge_management', 'data_analysis', 'critical_thinking'],
  Engineering: ['coding', 'data_analysis', 'automation', 'integration', 'app_development'],
  Manufacturing: ['automation', 'productivity', 'data_analysis', 'workflow', 'integration'],
  Entrepreneurship: ['strategy', 'decision_support', 'implementation', 'roi', 'marketing', 'agents'],
  Freelancing: ['productivity', 'writing', 'marketing', 'presentations', 'communication'],
  Student: ['research', 'writing', 'knowledge_management', 'productivity'],
  'Job Seeker': ['writing', 'communication', 'presentations', 'productivity'],
  'Content Creation': ['content', 'creative', 'multimedia', 'writing', 'marketing', 'campaigns'],
  'Customer Service': ['communication', 'workflow', 'automation', 'decision_support'],
  'Legal Services': ['research', 'verification', 'writing', 'knowledge_management', 'critical_thinking'],
  'Government Administration': ['governance', 'communication', 'decision_support', 'project_management', 'writing'],
  Other: [],
};

export const AI_EXPERIENCE_OPTIONS: string[] = [
  'Never used AI',
  'Tried AI a few times',
  'Use AI occasionally',
  'Use AI regularly',
  'Use AI for advanced workflows',
  'Build AI-powered solutions',
];

export const TOOLS_USED_OPTIONS: string[] = [
  'ChatGPT',
  'Claude',
  'Gemini',
  'Microsoft Copilot',
  'Perplexity',
  'Grok',
  'NotebookLM',
  'Canva AI',
  'Power BI',
  'n8n',
  'Zapier',
  'Make',
  'AI Coding Assistants',
  'None',
];

export const TIME_AVAILABLE_OPTIONS: string[] = [
  '15 minutes daily',
  '30 minutes daily',
  '1 hour daily',
  '2 hours daily',
  'Weekends only',
  'Custom schedule',
];

export const LEARNING_FORMAT_OPTIONS: string[] = [
  'YouTube videos',
  'PDF guides',
  'Interactive exercises',
  'Real-world projects',
  'Step-by-step tutorials',
  'Case studies',
  'Live practice',
];

export const OBJECTIVE_OPTIONS: string[] = [
  'Increase productivity',
  'Improve job performance',
  'Automate repetitive work',
  'Improve decision-making',
  'Develop AI technical skills',
  'Build a new career',
  'Create a business',
  'Become an AI implementation specialist',
  'Other',
];

export const OBJECTIVE_TO_TAGS: Record<string, string[]> = {
  'Increase productivity': ['productivity', 'workflow'],
  'Improve job performance': ['professional_workflow', 'implementation'],
  'Automate repetitive work': ['automation', 'integration'],
  'Improve decision-making': ['strategy', 'decision_support'],
  'Develop AI technical skills': ['coding', 'app_development', 'agents'],
  'Build a new career': ['implementation', 'capstone'],
  'Create a business': ['business', 'agents'],
  'Become an AI implementation specialist': ['implementation', 'professional_workflow', 'capstone'],
  Other: [],
};

export const PRIORITIES: PriorityItem[] = [
  { id: 'W01', name: 'Data Analysis', tags: ['data_analysis', 'excel', 'analytics'], primaryDimension: 'D04' },
  { id: 'W02', name: 'Marketing Campaign Creation', tags: ['marketing', 'content', 'strategy'], primaryDimension: 'D05' },
  { id: 'W03', name: 'Sales Planning and Forecasting', tags: ['sales', 'forecasting', 'analytics'], primaryDimension: 'D04' },
  { id: 'W04', name: 'Presentation Creation', tags: ['presentations', 'communication'], primaryDimension: 'D05' },
  { id: 'W05', name: 'Professional Writing', tags: ['writing', 'prompting'], primaryDimension: 'D05' },
  { id: 'W06', name: 'Research and Information Gathering', tags: ['research', 'verification'], primaryDimension: 'D03' },
  { id: 'W07', name: 'Image and Video Creation', tags: ['creative', 'multimedia'], primaryDimension: 'D05' },
  { id: 'W08', name: 'Excel and Spreadsheet Automation', tags: ['excel', 'data_analysis', 'automation'], primaryDimension: 'D04' },
  { id: 'W09', name: 'Workflow Automation', tags: ['automation', 'integration'], primaryDimension: 'D07' },
  { id: 'W10', name: 'Customer Communication', tags: ['communication', 'customer_service'], primaryDimension: 'D05' },
  { id: 'W11', name: 'Business Strategy Development', tags: ['strategy', 'decision_support'], primaryDimension: 'D10' },
  { id: 'W12', name: 'Coding and Application Development', tags: ['coding', 'app_development'], primaryDimension: 'D10' },
  { id: 'W13', name: 'AI Agents and Assistants', tags: ['agents', 'automation'], primaryDimension: 'D08' },
  { id: 'W14', name: 'Human Resources and Recruitment', tags: ['hr', 'communication', 'governance'], primaryDimension: 'D09' },
  { id: 'W15', name: 'Learning and Teaching', tags: ['education', 'learning'], primaryDimension: 'D05' },
  { id: 'W16', name: 'Project Management', tags: ['project_management', 'productivity'], primaryDimension: 'D07' },
  { id: 'W17', name: 'Medical or Scientific Information Analysis', tags: ['research', 'healthcare', 'verification'], primaryDimension: 'D03' },
  { id: 'W18', name: 'Personal Productivity', tags: ['productivity', 'workflow'], primaryDimension: 'D07' },
  { id: 'W19', name: 'Financial Reporting', tags: ['finance', 'data_analysis'], primaryDimension: 'D04' },
  { id: 'W20', name: 'Building an AI-Powered Business', tags: ['business', 'agents', 'automation'], primaryDimension: 'D10' },
];

export const PRIORITY_RANK_WEIGHTS = {
  rank_1: 5,
  rank_2: 3,
  rank_3: 2,
  selected_unranked: 1,
  not_selected: 0,
};

export const DIMENSIONS: DimensionItem[] = [
  { id: 'D01', name: 'AI Fundamentals' },
  { id: 'D02', name: 'Prompt Engineering' },
  { id: 'D03', name: 'Critical Thinking & Verification' },
  { id: 'D04', name: 'Data Literacy' },
  { id: 'D05', name: 'Content & Communication' },
  { id: 'D06', name: 'AI Tool Selection' },
  { id: 'D07', name: 'Workflow Integration' },
  { id: 'D08', name: 'Automation' },
  { id: 'D09', name: 'Responsible AI' },
  { id: 'D10', name: 'Practical Implementation' },
];

export const CORE_QUESTIONS: Question[] = [
  {
    id: 'Q01',
    dimensionId: 'D01',
    text: 'Which statement best describes generative AI?',
    options: [
      'It always provides verified facts.',
      'It can generate content based on learned patterns.',
      'It only works with numerical data.',
      'It independently guarantees correct decisions.',
    ],
    correctIndex: 1,
  },
  {
    id: 'Q02',
    dimensionId: 'D01',
    text: 'Which of these is a known limitation of current generative AI systems?',
    options: [
      'They always cite verifiable sources.',
      'They can produce confident-sounding but incorrect information.',
      'They understand context perfectly in every case.',
      'They never require human review.',
    ],
    correctIndex: 1,
  },
  {
    id: 'Q03',
    dimensionId: 'D02',
    text: 'Which prompt is most suitable for creating a targeted marketing plan?',
    options: [
      'Write marketing.',
      'Make something professional.',
      'Create a marketing plan for the specified audience, goal, budget, and timeframe, stating assumptions.',
      'Give me a great answer.',
    ],
    correctIndex: 2,
  },
  {
    id: 'Q04',
    dimensionId: 'D02',
    text: 'A useful AI prompt should clearly specify the task, relevant context, constraints, and expected...',
    options: ['mood', 'output format', 'length only', 'emoji'],
    correctIndex: 1,
  },
  {
    id: 'Q05',
    dimensionId: 'D03',
    text: 'An AI provides a medical statistic without a reference. What should you do?',
    options: [
      'Assume it is correct.',
      'Publish it immediately.',
      'Verify it using reliable original sources before use.',
      'Ask the same AI to repeat the statistic.',
    ],
    correctIndex: 2,
  },
  {
    id: 'Q06',
    dimensionId: 'D03',
    text: "An AI-generated sales report claims a 40% regional increase you can't find in the source data. Best next step?",
    options: [
      'Include it since AI generated it.',
      'Remove the report entirely.',
      'Trace the figure back to the original dataset before using it.',
      'Round the number down to be safe.',
    ],
    correctIndex: 2,
  },
  {
    id: 'Q07',
    dimensionId: 'D04',
    text: 'Which activities are useful when preparing data for analysis? (pick the best single answer)',
    options: [
      'Checking missing values, duplicates, and units together',
      'Only checking missing values',
      'Inventing missing values without disclosure',
      'Deleting any row with a blank cell',
    ],
    correctIndex: 0,
  },
  {
    id: 'Q08',
    dimensionId: 'D04',
    text: "Before using a spreadsheet column labeled 'Growth' in an analysis, what should you confirm?",
    options: [
      'Nothing, the column name is enough.',
      'What time period, unit, and calculation method it represents.',
      'That it is colored green.',
      'That it appears first in the sheet.',
    ],
    correctIndex: 1,
  },
  {
    id: 'Q09',
    dimensionId: 'D05',
    text: 'Which revision most improves an AI-drafted client email before sending?',
    options: [
      'Send it unedited to save time.',
      'Check tone, accuracy, and that it matches what was actually agreed with the client.',
      'Make it longer for thoroughness.',
      'Add technical jargon to sound expert.',
    ],
    correctIndex: 1,
  },
  {
    id: 'Q10',
    dimensionId: 'D05',
    text: 'What is the main risk of pasting an AI-written paragraph directly into a professional report without review?',
    options: [
      "It may contain inaccurate or generic claims that don't reflect your actual data.",
      'It will always be too short.',
      'It cannot be edited afterward.',
      "It voids the document's formatting.",
    ],
    correctIndex: 0,
  },
  {
    id: 'Q11',
    dimensionId: 'D06',
    text: 'A colleague wants to automate moving data between two apps without writing code. Which tool type best fits?',
    options: [
      'A general chatbot',
      'A no-code automation platform (e.g. Zapier, Make, n8n)',
      'A video generation tool',
      'A presentation tool',
    ],
    correctIndex: 1,
  },
  {
    id: 'Q12',
    dimensionId: 'D07',
    text: 'What should happen before automating a repetitive business process?',
    options: [
      'Automate every step immediately.',
      'Map the process, review risks, and define success criteria.',
      'Remove all human review.',
      'Purchase as many AI tools as possible.',
    ],
    correctIndex: 1,
  },
  {
    id: 'Q13',
    dimensionId: 'D08',
    text: 'What is a key risk of fully automating a customer-facing workflow with no human checkpoint?',
    options: [
      'It will run too slowly.',
      'Errors or edge cases may go uncaught and directly affect customers.',
      'It becomes impossible to automate further.',
      'It requires no monitoring ever.',
    ],
    correctIndex: 1,
  },
  {
    id: 'Q14',
    dimensionId: 'D09',
    text: 'What should you do before uploading confidential company data to an AI service?',
    options: [
      'Upload it without review.',
      "Check authorization, company policy, and the provider's data handling terms.",
      'Remove the document title and upload everything.',
      'Assume every AI service is private.',
    ],
    correctIndex: 1,
  },
  {
    id: 'Q15',
    dimensionId: 'D09',
    text: 'Your data includes identifiable client or patient information. Before analyzing it with an AI tool, you must first verify:',
    options: [
      "That the tool's output looks professional.",
      'Whether uploading this sensitive data is authorized and policy-compliant.',
      'That the AI has a Bangla language option.',
      'That the file is under 10MB.',
    ],
    correctIndex: 1,
  },
  {
    id: 'Q16',
    dimensionId: 'D10',
    text: 'A measurable result used to evaluate whether an AI project succeeded is commonly called a...',
    options: [
      'vibe check',
      'KPI (key performance indicator)',
      'screenshot',
      'press release',
    ],
    correctIndex: 1,
  },
];

export const ADAPTIVE_QUESTIONS: Question[] = [
  {
    id: 'A01',
    priorityId: 'W01',
    dimensionId: 'D04',
    text: 'When AI summarizes a dataset for you, what should you still do before presenting the summary?',
    options: [
      'Nothing extra.',
      'Spot-check key numbers against the raw data.',
      'Make slides immediately.',
      'Delete the raw data.',
    ],
    correctIndex: 1,
  },
  {
    id: 'A02',
    priorityId: 'W02',
    dimensionId: 'D05',
    text: 'What should an AI-generated campaign brief always include before execution?',
    options: [
      'Only a catchy slogan.',
      'Objective, target audience, channels, and success metrics.',
      'A random hashtag.',
      'Nothing — AI covers everything.',
    ],
    correctIndex: 1,
  },
  {
    id: 'A03',
    priorityId: 'W03',
    dimensionId: 'D04',
    text: 'An AI sales forecast looks unusually optimistic. What should you check first?',
    options: [
      'The chart colors.',
      'The assumptions and historical data it was built on.',
      'Nothing — trust the model.',
      "Whether it matches last year's forecast exactly.",
    ],
    correctIndex: 1,
  },
  {
    id: 'A04',
    priorityId: 'W04',
    dimensionId: 'D05',
    text: 'What makes an AI-assisted presentation actually audience-ready?',
    options: [
      'More slides.',
      'Accurate content, clear structure, and a message tailored to the audience.',
      'Maximum animations.',
      'The longest possible speaker notes.',
    ],
    correctIndex: 1,
  },
  {
    id: 'A05',
    priorityId: 'W05',
    dimensionId: 'D05',
    text: 'The best way to use AI for a first draft of a professional document is to:',
    options: [
      'Publish it as-is.',
      'Use it as a starting point, then revise for accuracy, tone, and your own voice.',
      'Never read it before sending.',
      'Ask AI to sign it.',
    ],
    correctIndex: 1,
  },
  {
    id: 'A06',
    priorityId: 'W06',
    dimensionId: 'D03',
    text: 'When AI summarizes research for you, the most important habit is to:',
    options: [
      'Trust every claim.',
      'Trace important claims back to original, verifiable sources.',
      'Only read the summary.',
      'Never check dates.',
    ],
    correctIndex: 1,
  },
  {
    id: 'A07',
    priorityId: 'W07',
    dimensionId: 'D05',
    text: 'Before using an AI-generated image in official company material, you should check:',
    options: [
      'File size only.',
      'Rights, brand fit, and factual accuracy of any depicted details.',
      'Nothing.',
      "That it's colorful.",
    ],
    correctIndex: 1,
  },
  {
    id: 'A08',
    priorityId: 'W08',
    dimensionId: 'D04',
    text: 'AI suggests a spreadsheet formula to automate a report. Before relying on it, you should:',
    options: [
      'Apply it to all future files immediately.',
      'Test it against a known correct result first.',
      'Delete the original formula.',
      'Ignore any errors it produces.',
    ],
    correctIndex: 1,
  },
  {
    id: 'A09',
    priorityId: 'W09',
    dimensionId: 'D07',
    text: 'The first step in automating a business workflow with AI or no-code tools is to:',
    options: [
      'Automate every step at once.',
      'Map the current process and find where automation adds real value.',
      'Buy the most expensive tool.',
      'Skip planning.',
    ],
    correctIndex: 1,
  },
  {
    id: 'A10',
    priorityId: 'W10',
    dimensionId: 'D05',
    text: "What's the risk of letting AI auto-send customer replies with no review?",
    options: [
      "None — it's always accurate.",
      'It might send incorrect or inappropriate information under the company’s name.',
      'Customers prefer it.',
      'It saves no time.',
    ],
    correctIndex: 1,
  },
  {
    id: 'A11',
    priorityId: 'W11',
    dimensionId: 'D10',
    text: 'AI can help explore strategic options, but final decisions should:',
    options: [
      'Be made entirely by AI.',
      "Remain with human judgment, weighing risks AI can't fully assess.",
      'Be automated with no oversight.',
      'Depend on which option AI lists first.',
    ],
    correctIndex: 1,
  },
  {
    id: 'A12',
    priorityId: 'W12',
    dimensionId: 'D10',
    text: 'When AI writes code for you, before using it in production you should:',
    options: [
      'Deploy immediately.',
      'Review, test, and understand what it actually does.',
      'Never read it.',
      "Assume it's bug-free.",
    ],
    correctIndex: 1,
  },
  {
    id: 'A13',
    priorityId: 'W13',
    dimensionId: 'D08',
    text: 'A safe AI agent design gives it:',
    options: [
      'Unlimited access to every system.',
      'Clearly scoped permissions and a human checkpoint for risky actions.',
      'No logging.',
      'Full autonomy with no limits.',
    ],
    correctIndex: 1,
  },
  {
    id: 'A14',
    priorityId: 'W14',
    dimensionId: 'D09',
    text: 'Using AI to screen job candidates requires extra care because:',
    options: [
      "It's always unbiased.",
      'It can encode bias from training data and needs human oversight and fairness checks.',
      'It never needs review.',
      "Candidates won't notice.",
    ],
    correctIndex: 1,
  },
  {
    id: 'A15',
    priorityId: 'W15',
    dimensionId: 'D05',
    text: 'AI can support teaching best when it is used to:',
    options: [
      'Replace the teacher entirely.',
      'Personalize practice and explanations while a person still assesses real understanding.',
      'Grade everything with no review.',
      'Discourage questions.',
    ],
    correctIndex: 1,
  },
  {
    id: 'A16',
    priorityId: 'W16',
    dimensionId: 'D07',
    text: 'AI-generated project timelines should be treated as:',
    options: [
      'Final and fixed.',
      'A useful draft to validate against real constraints and team capacity.',
      'Unnecessary to review.',
      'Always accurate to the day.',
    ],
    correctIndex: 1,
  },
  {
    id: 'A17',
    priorityId: 'W17',
    dimensionId: 'D03',
    text: 'When AI summarizes medical or scientific literature, you must:',
    options: [
      'Trust it as clinical fact.',
      'Verify claims against primary, peer-reviewed sources before any professional use.',
      'Skip verification to save time.',
      'Never mention AI was used.',
    ],
    correctIndex: 1,
  },
  {
    id: 'A18',
    priorityId: 'W18',
    dimensionId: 'D07',
    text: 'The most sustainable way to use AI for personal productivity is to:',
    options: [
      'Automate everything blindly.',
      'Start with one recurring task, measure the time saved, then expand.',
      'Change tools every week.',
      'Avoid any routine.',
    ],
    correctIndex: 1,
  },
  {
    id: 'A19',
    priorityId: 'W19',
    dimensionId: 'D04',
    text: 'Before including an AI-calculated figure in a financial report, you should:',
    options: [
      "Assume it's correct.",
      'Verify the calculation and source data independently.',
      'Round it for simplicity.',
      'Remove the source reference.',
    ],
    correctIndex: 1,
  },
  {
    id: 'A20',
    priorityId: 'W20',
    dimensionId: 'D10',
    text: 'A viable AI-powered business idea needs, above all:',
    options: [
      'The newest possible AI model.',
      'A real customer problem, a clear value proposition, and a sustainable way to deliver it.',
      'A large marketing budget only.',
      'No competitors ever.',
    ],
    correctIndex: 1,
  },
];

export const TAG_TO_DIMENSION_MAP: Record<string, string> = {
  ai_fundamentals: 'D01',
  prompting: 'D02',
  workflow: 'D07',
  verification: 'D03',
  critical_thinking: 'D03',
  privacy: 'D09',
  governance: 'D09',
  writing: 'D05',
  communication: 'D05',
  research: 'D03',
  excel: 'D04',
  data_analysis: 'D04',
  analytics: 'D04',
  visualization: 'D04',
  presentations: 'D05',
  marketing: 'D05',
  campaigns: 'D05',
  content: 'D05',
  creative: 'D05',
  multimedia: 'D05',
  sales: 'D04',
  strategy: 'D10',
  decision_support: 'D10',
  productivity: 'D07',
  automation: 'D08',
  integration: 'D08',
  coding: 'D10',
  app_development: 'D10',
  agents: 'D08',
  knowledge_management: 'D03',
  implementation: 'D10',
  professional_workflow: 'D10',
  roi: 'D10',
  capstone: 'D10',
  tool_selection: 'D06',
  forecasting: 'D04',
  customer_service: 'D05',
  hr: 'D09',
  education: 'D05',
  project_management: 'D07',
  healthcare: 'D03',
  finance: 'D04',
  business: 'D10',
  learning: 'D05',
};

export const MODULES: ModuleItem[] = [
  {
    id: 'M01',
    title: 'AI Fundamentals and Generative AI',
    level: 'Foundation',
    hours: 3,
    tags: ['ai_fundamentals'],
    prereq: [],
    category: 'fundamentals',
    outcome: 'Explain what AI can and cannot reliably do.',
    task: 'Identify five relevant AI applications in your own profession.',
    lesson: "Generative AI produces new text, images, or code by predicting patterns learned from data — it does not 'know' facts the way a database does, and it can sound confident while being wrong. This module builds a working mental model of what these systems are actually good at, and where they quietly fail.",
  },
  {
    id: 'M02',
    title: 'AI Tools and Platform Selection',
    level: 'Foundation',
    hours: 3,
    tags: ['tool_selection'],
    prereq: ['M01'],
    category: 'fundamentals',
    outcome: 'Select suitable AI tools using capability, cost, privacy, and workflow fit.',
    task: 'Compare three tools for one real task you do regularly.',
    lesson: 'Not every AI tool suits every job — a chat assistant, a spreadsheet AI, and a no-code automation platform solve different problems. You will learn a simple checklist for matching a task to the right category of tool instead of defaulting to whichever one is trending.',
  },
  {
    id: 'M03',
    title: 'Prompt Engineering Fundamentals',
    level: 'Foundation',
    hours: 5,
    tags: ['prompting'],
    prereq: ['M01'],
    category: 'prompting',
    outcome: 'Create clear, contextual, structured prompts.',
    task: 'Develop five prompts for tasks you do at least weekly.',
    lesson: 'A vague prompt gets a vague answer. This module covers the four things a strong prompt almost always states explicitly: the task, the context, the constraints, and the format you expect the output in.',
  },
  {
    id: 'M04',
    title: 'Advanced Prompt Engineering',
    level: 'Intermediate',
    hours: 5,
    tags: ['prompting', 'workflow'],
    prereq: ['M03'],
    category: 'prompting',
    outcome: 'Build reusable prompt templates with examples and evaluation criteria.',
    task: 'Create and test a small prompt library for one recurring workflow.',
    lesson: "Once basic prompting is second nature, the next gain comes from reusable templates: filling in variables, giving the model examples of what 'good' looks like, and defining how you will judge the output before you ever run it.",
  },
  {
    id: 'M05',
    title: 'AI Accuracy, Verification and Critical Thinking',
    level: 'Foundation',
    hours: 4,
    tags: ['verification', 'critical_thinking'],
    prereq: ['M01'],
    category: 'verification',
    outcome: 'Identify hallucinations, unsupported claims, and unreliable outputs.',
    task: 'Audit an AI-generated report and verify its important claims against sources.',
    lesson: 'AI models can fabricate statistics, citations, and quotes with total confidence. This module is about building the habit of tracing any claim that matters back to something you can actually verify.',
  },
  {
    id: 'M06',
    title: 'Responsible AI, Privacy and Security',
    level: 'Foundation',
    hours: 4,
    tags: ['privacy', 'governance'],
    prereq: ['M01'],
    category: 'verification',
    outcome: 'Use AI while protecting sensitive information and keeping a human accountable.',
    task: 'Write a personal or team AI safety checklist.',
    lesson: 'Before pasting anything into an AI tool — a client list, patient data, unreleased financials — you need a quick way to check whether that is actually permitted. This module gives you that checklist.',
  },
  {
    id: 'M07',
    title: 'AI-Powered Professional Writing',
    level: 'Intermediate',
    hours: 4,
    tags: ['writing', 'communication'],
    prereq: ['M03', 'M05'],
    category: 'communication',
    outcome: 'Produce and review effective professional communication.',
    task: 'Draft a report, an email, and an executive summary for a real task.',
    lesson: 'AI is a strong first-draft partner for professional writing, but tone, accuracy, and what was actually agreed with a client are things only you can confirm. This module covers drafting fast and editing well.',
  },
  {
    id: 'M08',
    title: 'AI Research and Knowledge Management',
    level: 'Intermediate',
    hours: 5,
    tags: ['research', 'verification'],
    prereq: ['M03', 'M05'],
    category: 'verification',
    outcome: 'Research topics using traceable sources and organize reliable findings.',
    task: 'Prepare a source-verified research brief on a real topic.',
    lesson: 'Good AI-assisted research means every important finding can be traced to a real, checkable source — not just a fluent-sounding paragraph. You will practice building a brief that could survive a colleague fact-checking it.',
  },
  {
    id: 'M09',
    title: 'AI for Excel and Spreadsheet Productivity',
    level: 'Intermediate',
    hours: 6,
    tags: ['excel', 'data_analysis'],
    prereq: ['M03', 'M06'],
    category: 'data',
    outcome: 'Use AI to support spreadsheet cleaning, formulas, and reporting.',
    task: 'Turn a sample dataset into a usable spreadsheet report.',
    lesson: 'AI can suggest formulas, clean messy columns, and draft summaries, but every formula it proposes should be tested against a result you already know is correct. This module builds that verify-then-trust habit.',
  },
  {
    id: 'M10',
    title: 'AI Data Analysis and Business Analytics',
    level: 'Intermediate',
    hours: 8,
    tags: ['data_analysis', 'analytics'],
    prereq: ['M05', 'M09'],
    category: 'data',
    outcome: 'Analyze structured data and separate findings from unsupported interpretation.',
    task: 'Complete an end-to-end analysis of a sample business dataset.',
    lesson: 'Analytics with AI moves fast — sometimes too fast. This module works through a full analysis while flagging the exact moments where a plausible-sounding conclusion needs a second check against the raw numbers.',
  },
  {
    id: 'M11',
    title: 'AI Dashboards and Data Visualization',
    level: 'Intermediate',
    hours: 6,
    tags: ['visualization', 'analytics'],
    prereq: ['M09', 'M10'],
    category: 'data',
    outcome: 'Convert validated data into clear, honest charts and dashboards.',
    task: 'Build an interactive dashboard with meaningful KPIs.',
    lesson: 'A chart can make a weak number look strong. This module focuses on choosing visuals that represent the data honestly, and on picking KPIs that actually matter to the decision being made.',
  },
  {
    id: 'M12',
    title: 'AI Presentation and Business Storytelling',
    level: 'Intermediate',
    hours: 5,
    tags: ['presentations', 'communication'],
    prereq: ['M03', 'M05'],
    category: 'communication',
    outcome: 'Create structured, accurate, audience-focused presentations.',
    task: 'Prepare a ten-slide presentation for a real audience.',
    lesson: 'A good AI-assisted deck starts with a message, not a slide count. You will practice structuring a talk track first, then using AI to speed up the slide-by-slide execution.',
  },
  {
    id: 'M13',
    title: 'AI Marketing Campaign Creator',
    level: 'Intermediate',
    hours: 8,
    tags: ['marketing', 'campaigns', 'content'],
    prereq: ['M03', 'M05', 'M06'],
    category: 'communication',
    outcome: 'Design audience-specific campaigns with objectives, messaging, channels, and KPIs.',
    task: 'Develop a complete campaign for a sample product or service.',
    lesson: 'A campaign brief needs an objective, a defined audience, a channel plan, and a way to know if it worked — AI can draft all four quickly, but you decide whether they actually fit the market.',
  },
  {
    id: 'M14',
    title: 'AI Image, Design and Video Creation',
    level: 'Intermediate',
    hours: 7,
    tags: ['creative', 'multimedia'],
    prereq: ['M03', 'M06'],
    category: 'communication',
    outcome: 'Create and evaluate visual assets with appropriate AI tools.',
    task: 'Develop a coordinated set of visual marketing materials.',
    lesson: 'Generating an image is easy; generating one that is on-brand, accurate, and cleared to use is the actual skill. This module covers both the tools and the review step before anything ships.',
  },
  {
    id: 'M15',
    title: 'AI Sales Intelligence and Customer Strategy',
    level: 'Intermediate',
    hours: 7,
    tags: ['sales', 'analytics', 'strategy'],
    prereq: ['M03', 'M05', 'M06'],
    category: 'strategy',
    outcome: 'Apply AI to sales planning, segmentation, and customer communication.',
    task: 'Create a measurable sales improvement plan using sample data.',
    lesson: 'AI can spot patterns across a territory or customer base faster than a manual review — the skill is turning that pattern into a specific, measurable plan rather than a vague observation.',
  },
  {
    id: 'M16',
    title: 'AI for Business Strategy and Decision Support',
    level: 'Advanced',
    hours: 7,
    tags: ['strategy', 'decision_support'],
    prereq: ['M05', 'M10'],
    category: 'strategy',
    outcome: 'Use AI to explore business scenarios while keeping human judgment central.',
    task: 'Prepare a strategic options analysis with stated assumptions and risks.',
    lesson: 'AI is genuinely useful for laying out options and their trade-offs side by side. The judgment about which risk is acceptable stays with you — this module practices keeping that line clear.',
  },
  {
    id: 'M17',
    title: 'AI Productivity and Workflow Optimization',
    level: 'Intermediate',
    hours: 5,
    tags: ['productivity', 'workflow'],
    prereq: ['M03', 'M06'],
    category: 'automation',
    outcome: 'Redesign a repetitive task to save real time.',
    task: 'Document and improve one recurring workflow you own.',
    lesson: 'Before automating anything, it helps to actually map the steps you take today. This module starts there, then looks for the two or three steps where AI genuinely removes friction.',
  },
  {
    id: 'M18',
    title: 'No-Code AI Workflow Automation',
    level: 'Advanced',
    hours: 10,
    tags: ['automation', 'integration'],
    prereq: ['M06', 'M17'],
    category: 'automation',
    outcome: 'Build safe automation workflows using no-code tools.',
    task: 'Build and test an automation using synthetic data.',
    lesson: "No-code platforms let you connect apps and trigger actions without writing code — the risk shifts from 'can I build this' to 'what happens when it fails silently.' This module covers both.",
  },
  {
    id: 'M19',
    title: 'AI Coding and Application Development',
    level: 'Advanced',
    hours: 12,
    tags: ['coding', 'app_development'],
    prereq: ['M03', 'M05', 'M06'],
    category: 'implementation',
    outcome: 'Use AI coding assistance to develop and test a small application.',
    task: 'Create and validate a functional interactive application.',
    lesson: "AI can write working code quickly, but 'runs without errors' is not the same as 'correct.' This module practices reading, testing, and understanding AI-generated code before it goes anywhere near real use.",
  },
  {
    id: 'M20',
    title: 'Custom AI Assistants and AI Agents',
    level: 'Advanced',
    hours: 10,
    tags: ['agents', 'automation'],
    prereq: ['M04', 'M06', 'M17'],
    category: 'automation',
    outcome: 'Design bounded AI assistants with clear permissions and human oversight.',
    task: 'Create and evaluate a task-specific AI assistant.',
    lesson: 'An AI agent that can take real actions needs real limits — what it is allowed to touch, and where a human has to sign off. This module is about designing those boundaries deliberately, not as an afterthought.',
  },
  {
    id: 'M21',
    title: 'AI Knowledge Bases and Document Intelligence',
    level: 'Advanced',
    hours: 8,
    tags: ['research', 'knowledge_management'],
    prereq: ['M05', 'M06', 'M08'],
    category: 'verification',
    outcome: 'Build document-supported question-answering workflows with source traceability.',
    task: 'Develop a small knowledge assistant using authorized sample documents.',
    lesson: 'A knowledge assistant is only useful if you can trust its answers — which means every answer should point back to a specific passage in a specific, authorized document.',
  },
  {
    id: 'M22',
    title: 'Profession-Specific AI Implementation',
    level: 'Advanced',
    hours: 8,
    tags: ['implementation', 'professional_workflow'],
    prereq: ['M05', 'M06', 'M17'],
    category: 'implementation',
    outcome: 'Map AI capabilities to your real day-to-day responsibilities.',
    task: 'Develop an AI implementation plan for your own role.',
    lesson: 'This is where the training stops being generic. You will take your own three most important responsibilities and work out, concretely, where AI fits and where it does not.',
  },
  {
    id: 'M23',
    title: 'AI Project Management and ROI Measurement',
    level: 'Advanced',
    hours: 6,
    tags: ['project_management', 'roi'],
    prereq: ['M17', 'M22'],
    category: 'strategy',
    outcome: 'Plan an AI project, define KPIs, estimate cost, and evaluate real outcomes.',
    task: 'Create a practical AI project charter and evaluation framework.',
    lesson: 'An AI initiative that cannot say whether it worked usually gets quietly abandoned. This module builds the habit of defining success metrics before the project starts, not after.',
  },
  {
    id: 'M24',
    title: 'Final AI Implementation Capstone',
    level: 'Applied',
    hours: 12,
    tags: ['implementation', 'capstone'],
    prereq: ['M05', 'M06', 'M22'],
    category: 'implementation',
    outcome: 'Demonstrate an end-to-end AI solution to a real professional problem.',
    task: 'Build, test, document, and present one complete AI implementation project.',
    lesson: 'The capstone pulls everything together: a real problem from your own work, an AI-supported solution, a verification step, and a short write-up of what it actually changed.',
  },
];

export const QUIZ_POOLS: Record<ModuleCategory, QuizQuestion[]> = {
  fundamentals: [
    {
      text: 'What is the safest assumption about an AI-generated answer you haven’t checked?',
      options: [
        'It’s correct.',
        'It might be wrong and should be checked if it matters.',
        'It’s always better than a human answer.',
        'It never needs a source.',
      ],
      correctIndex: 1,
    },
    {
      text: 'AI models generate output by:',
      options: [
        'Looking up a fixed database of facts.',
        'Predicting likely patterns based on training data.',
        'Calling a human expert in real time.',
        'Randomly guessing every word.',
      ],
      correctIndex: 1,
    },
    {
      text: 'Choosing the right AI tool for a task depends mainly on:',
      options: [
        'Which tool is newest.',
        'Capability fit, cost, privacy, and workflow fit.',
        'Which tool has the most followers.',
        'Whichever tool is free.',
      ],
      correctIndex: 1,
    },
    {
      text: 'A confident-sounding but false AI output is usually called:',
      options: [
        'A hallucination.',
        'A firmware bug.',
        'A cache miss.',
        'A syntax error.',
      ],
      correctIndex: 0,
    },
    {
      text: 'Before trusting an AI tool with a new type of task, it helps to:',
      options: [
        'Test it on something you can already verify.',
        'Assume it will work perfectly.',
        'Skip testing to save time.',
        'Only use it for the biggest, riskiest task first.',
      ],
      correctIndex: 0,
    },
  ],
  prompting: [
    {
      text: 'A strong prompt typically states:',
      options: [
        'Just the topic.',
        'The task, context, constraints, and expected format.',
        'Only the desired word count.',
        'Nothing beyond a single keyword.',
      ],
      correctIndex: 1,
    },
    {
      text: 'Giving an AI model an example of the output you want is called:',
      options: [
        'Few-shot prompting.',
        'Zero information.',
        'Reverse engineering.',
        'Blind testing.',
      ],
      correctIndex: 0,
    },
    {
      text: 'A reusable prompt template is most useful when:',
      options: [
        'You do a task once.',
        'You do a similar task repeatedly.',
        'The task has no variables.',
        'You never plan to edit it.',
      ],
      correctIndex: 1,
    },
    {
      text: 'If an AI’s first answer misses the mark, the best move is usually to:',
      options: [
        'Give up on AI for this task.',
        'Refine the prompt with more specific context or constraints.',
        'Repeat the exact same prompt.',
        'Assume the task is impossible.',
      ],
      correctIndex: 1,
    },
    {
      text: 'Defining “expected output format” in a prompt helps because it:',
      options: [
        'Makes the AI faster only.',
        'Reduces back-and-forth by setting clear expectations upfront.',
        'Is required by law.',
        'Prevents any errors entirely.',
      ],
      correctIndex: 1,
    },
  ],
  verification: [
    {
      text: 'The most reliable way to check an AI-cited statistic is to:',
      options: [
        'Ask the same AI again.',
        'Trace it to an original, checkable source.',
        'Assume repetition means it’s true.',
        'Ignore it if it sounds plausible.',
      ],
      correctIndex: 1,
    },
    {
      text: 'Before uploading sensitive company data to an AI tool, you should:',
      options: [
        'Just do it, it’s usually fine.',
        'Confirm authorization and the tool’s data-handling policy.',
        'Rename the file first.',
        'Compress the file first.',
      ],
      correctIndex: 1,
    },
    {
      text: 'A one-quote-per-source habit in research means:',
      options: [
        'Never quoting anything.',
        'Using at most one direct quote per source and paraphrasing the rest.',
        'Quoting every sentence.',
        'Quoting only headlines.',
      ],
      correctIndex: 1,
    },
    {
      text: 'An AI-drafted claim with no source should be treated as:',
      options: [
        'Fact.',
        'Unverified until checked.',
        'Automatically false.',
        'Irrelevant.',
      ],
      correctIndex: 1,
    },
    {
      text: 'Human oversight in AI-assisted decisions matters most when:',
      options: [
        'The stakes or sensitivity are low.',
        'The stakes, sensitivity, or ambiguity are high.',
        'The task is fully repetitive.',
        'AI has done it before without issue.',
      ],
      correctIndex: 1,
    },
  ],
  data: [
    {
      text: 'Before analyzing a spreadsheet column, you should confirm:',
      options: [
        'Its color.',
        'Its unit, time period, and how it was calculated.',
        'Its row count only.',
        'Nothing — trust the header.',
      ],
      correctIndex: 1,
    },
    {
      text: 'An AI-suggested formula should be:',
      options: [
        'Applied everywhere immediately.',
        'Tested against a known correct result first.',
        'Ignored entirely.',
        'Used only if it looks complex.',
      ],
      correctIndex: 1,
    },
    {
      text: 'A dashboard is most useful when its KPIs:',
      options: [
        'Look visually impressive.',
        'Actually relate to the decision being made.',
        'Include as many metrics as possible.',
        'Change color randomly.',
      ],
      correctIndex: 1,
    },
    {
      text: 'When AI finds a pattern in data, the next step is usually to:',
      options: [
        'Publish it immediately as a finding.',
        'Check whether the pattern holds up against the raw data.',
        'Ignore it.',
        'Assume causation automatically.',
      ],
      correctIndex: 1,
    },
    {
      text: 'Cleaning data before analysis should include:',
      options: [
        'Checking for missing values and duplicates.',
        'Deleting all rows with any blank cell.',
        'Inventing missing values.',
        'Skipping validation to save time.',
      ],
      correctIndex: 0,
    },
  ],
  communication: [
    {
      text: 'An AI first draft of a client email should be:',
      options: [
        'Sent immediately.',
        'Reviewed for tone, accuracy, and what was actually agreed.',
        'Made as long as possible.',
        'Sent without your name on it.',
      ],
      correctIndex: 1,
    },
    {
      text: 'A strong presentation built with AI assistance starts with:',
      options: [
        'The slide template.',
        'A clear message for the specific audience.',
        'The maximum number of slides.',
        'Background music.',
      ],
      correctIndex: 1,
    },
    {
      text: 'Before using an AI-generated image in official material, check:',
      options: [
        'Only its resolution.',
        'Licensing, brand fit, and factual accuracy.',
        'Nothing.',
        'Its file size only.',
      ],
      correctIndex: 1,
    },
    {
      text: 'A campaign brief should define, at minimum:',
      options: [
        'A slogan only.',
        'Objective, audience, channels, and success metrics.',
        'A budget only.',
        'Nothing beyond a headline.',
      ],
      correctIndex: 1,
    },
    {
      text: 'The biggest risk of unreviewed AI-written customer replies is:',
      options: [
        'They take longer to write.',
        'They may contain incorrect or inappropriate content sent under your name.',
        'Customers will notice they’re AI-written.',
        'None — it’s always safe.',
      ],
      correctIndex: 1,
    },
  ],
  automation: [
    {
      text: 'Before automating a workflow, the first step is to:',
      options: [
        'Automate everything at once.',
        'Map the current process and find where automation adds value.',
        'Buy the most expensive tool available.',
        'Skip any planning.',
      ],
      correctIndex: 1,
    },
    {
      text: 'A fully automated customer-facing process with no human checkpoint risks:',
      options: [
        'Running too fast.',
        'Letting errors or edge cases reach customers unnoticed.',
        'Becoming impossible to change.',
        'Nothing significant.',
      ],
      correctIndex: 1,
    },
    {
      text: 'A well-designed AI agent should have:',
      options: [
        'Unlimited access to all systems.',
        'Clearly scoped permissions and human checkpoints for risky actions.',
        'No monitoring.',
        'Full autonomy always.',
      ],
      correctIndex: 1,
    },
    {
      text: 'When testing a new automation, it’s best to use:',
      options: [
        'Live customer data immediately.',
        'Synthetic or sample data first.',
        'No data at all.',
        'Only worst-case data.',
      ],
      correctIndex: 1,
    },
    {
      text: 'A sustainable way to expand AI-driven productivity gains is to:',
      options: [
        'Automate every task on day one.',
        'Start with one task, measure the time saved, then expand.',
        'Change tools weekly.',
        'Skip measurement entirely.',
      ],
      correctIndex: 1,
    },
  ],
  strategy: [
    {
      text: 'When AI lays out strategic options, the final call should:',
      options: [
        'Default to AI’s top suggestion.',
        'Remain with human judgment weighing risks AI may not see.',
        'Be skipped entirely.',
        'Go to whichever option is cheapest only.',
      ],
      correctIndex: 1,
    },
    {
      text: 'An AI sales forecast that looks unusually optimistic should prompt you to:',
      options: [
        'Accept it immediately.',
        'Check its underlying assumptions and data.',
        'Ignore it.',
        'Double it for safety.',
      ],
      correctIndex: 1,
    },
    {
      text: 'A good AI project charter defines success:',
      options: [
        'After the project ends.',
        'Before the project starts, with clear KPIs.',
        'Never — success is subjective.',
        'Only in hindsight.',
      ],
      correctIndex: 1,
    },
    {
      text: 'Turning an AI-spotted data pattern into a real sales plan requires:',
      options: [
        'Repeating the pattern back as-is.',
        'Translating it into a specific, measurable action.',
        'Ignoring the pattern.',
        'Nothing further.',
      ],
      correctIndex: 1,
    },
    {
      text: 'AI-driven business decisions carry the most risk when:',
      options: [
        'Stakes are low and reversible.',
        'Stakes are high and hard to reverse, with no human review.',
        'The task is repetitive.',
        'Data is abundant and clean.',
      ],
      correctIndex: 1,
    },
  ],
  implementation: [
    {
      text: 'Before using AI-generated code in production, you should:',
      options: [
        'Deploy it immediately.',
        'Review, test, and understand what it does.',
        'Assume it’s bug-free.',
        'Never read it.',
      ],
      correctIndex: 1,
    },
    {
      text: 'An AI implementation plan for your own role should start from:',
      options: [
        'A generic template with no changes.',
        'Your actual top responsibilities and where AI genuinely helps.',
        'Whatever AI is trending.',
        'Nothing — just start building.',
      ],
      correctIndex: 1,
    },
    {
      text: 'Measuring whether an AI project succeeded requires:',
      options: [
        'A KPI defined in advance.',
        'A gut feeling afterward.',
        'Nothing — success is assumed.',
        'Comparing it to unrelated projects.',
      ],
      correctIndex: 0,
    },
    {
      text: 'A capstone AI project should be evaluated by:',
      options: [
        'How impressive it looks.',
        'Whether it verifiably solves the real problem it targeted.',
        'How much code it contains.',
        'How fast it was built.',
      ],
      correctIndex: 1,
    },
    {
      text: 'The riskiest part of most AI implementation projects is usually:',
      options: [
        'The AI model itself.',
        'Skipping verification and human review of the output.',
        'Choosing a project name.',
        'Using a spreadsheet.',
      ],
      correctIndex: 1,
    },
  ],
};

export interface ReadingResource {
  title: string;
  url: string;
  note: string;
}

export const PDF_OR_READING_LINKS: Record<string, ReadingResource> = {
  fundamentals: {
    title: 'Elements of AI — free introductory course (University of Helsinki & MinnaLearn)',
    url: 'https://www.elementsofai.com/',
    note: 'Not a PDF — the closest verified free material for this module’s topic is a self-paced course rather than a downloadable guide.',
  },
  prompting: {
    title: 'Google — Google Workspace with Gemini: Prompting Guide (PDF, 71 pages)',
    url: 'https://services.google.com/fh/files/misc/workspace_with_gemini_prompting_guide.pdf',
    note: 'Direct PDF from Google, checked and working. Covers persona/task/context/format prompting with real, role-based examples.',
  },
  communication: {
    title: 'Google — Google Workspace with Gemini: Prompting Guide (PDF)',
    url: 'https://services.google.com/fh/files/misc/workspace_with_gemini_prompting_guide.pdf',
    note: 'Same Google PDF — its dedicated sections on communications, customer service, HR and marketing writing are the closest verified match for this module.',
  },
  automation: {
    title: 'Google / Kaggle — “Agents” whitepaper',
    url: 'https://www.kaggle.com/whitepaper-agents',
    note: 'Official Google whitepaper on generative AI agents, hosted on Kaggle. A free Kaggle account may be needed to download the PDF itself.',
  },
};

export interface VideoResource {
  title: string;
  url: string;
}

export const VIDEO_LINKS: Record<ModuleCategory, VideoResource[]> = {
  fundamentals: [
    {
      title: 'What Can Generative AI Really Do? 2025 Overview — IBM',
      url: 'https://www.youtube.com/watch?v=jr6NogR3GRk',
    },
    {
      title: 'What is Generative AI? Explained in 60 Seconds',
      url: 'https://www.youtube.com/watch?v=KhpF1Y7f6-0',
    },
  ],
  prompting: [
    {
      title: 'Prompt Engineering: A Beginner’s Guide — IBM',
      url: 'https://www.youtube.com/watch?v=OeVzbJ6XwYs',
    },
    {
      title: 'Prompt Engineering Guide: 2026 Edition',
      url: 'https://www.youtube.com/watch?v=zAkMuMddM2E',
    },
  ],
  verification: [
    {
      title: 'Understanding AI Agent Hallucination in AI Systems — IBM',
      url: 'https://www.youtube.com/watch?v=bNRhppHct54',
    },
    {
      title: 'Fact-Checking with AI: How to Spot & Stop Hallucinations',
      url: 'https://www.youtube.com/watch?v=J2EUUE_1qa8',
    },
  ],
  data: [
    {
      title: 'Data Literacy vs AI Literacy Explained',
      url: 'https://www.youtube.com/watch?v=17cdidQdacM',
    },
    {
      title: 'What is Data Literacy? (2026)',
      url: 'https://www.youtube.com/watch?v=ZUnpvQgPLnw',
    },
  ],
  communication: [
    {
      title: 'Two ways to build customer service AI (and why it matters now)',
      url: 'https://www.youtube.com/watch?v=k8ol1JdgTgI',
    },
    {
      title: 'The Top 1% Build AI Presentations Differently — Jeff Su',
      url: 'https://www.youtube.com/watch?v=ZpXN9M0WLQ4',
    },
  ],
  automation: [
    {
      title: 'The Power of AI Agents and Agentic AI Explained — IBM',
      url: 'https://www.youtube.com/watch?v=2j26a5dmCnI',
    },
    {
      title: 'AI Agents, Clearly Explained — Jeff Su',
      url: 'https://www.youtube.com/watch?v=FwOTs4UxQS4',
    },
  ],
  strategy: [
    {
      title: 'AI Strategy Explained: How to Turn AI into Real Business Value',
      url: 'https://www.youtube.com/watch?v=JxGNflWYgcY',
    },
    {
      title: 'Why Your Business Needs an AI Strategy in 2026',
      url: 'https://www.youtube.com/watch?v=D3h1pBvnZRI',
    },
  ],
  implementation: [
    {
      title: 'IBM’s Global Managing Partner on how CEOs Are Rethinking AI ROI',
      url: 'https://www.youtube.com/watch?v=cJtcFPloZk8',
    },
    {
      title: 'How To Measure Enterprise AI ROI?',
      url: 'https://www.youtube.com/watch?v=qE7CghkGRI4',
    },
  ],
};

export const DAILY_MINUTES_MAP: Record<string, number> = {
  '15 minutes daily': 15,
  '30 minutes daily': 30,
  '1 hour daily': 60,
  '2 hours daily': 120,
  'Weekends only': 90,
  'Custom schedule': 30,
};
